### ISSUE TITLE
役割分担

### ISSUE THREAD

**Issue by Aono082** [ehimetakahashilab/TPI_implementation#1]
TPI作成のプログラムのひな型を作りました。
main関数に大まかなプログラムの流れを記載していますが、
現在は、回路テーブルの構造体作成と前方方向および後方方向の計算順序の決定までです。
回路テーブルの構造体に制御性、可観測性、故障伝搬数、BbCcメトリクスを用意しています。
自分のほうで、制御性、可観測性、故障伝搬数の計算を作成しておきます。
論文を読んでアルゴリズムの妥当性を確認しましたら、
中岡のほうでBbCcを計算するアルゴリズムを作成してください。

**Comment by NorihiroNakaoka** [comment]
テンプレート，役割分担ありがとうございます．
