### ISSUE TITLE
BbCcメトリクスの計算

### ISSUE THREAD

**Issue by MaineK00n** [ehimetakahashilab/TPI_implementation#2]

**Comment by Aono082** [comment]
s27回路で各ゲートを0,1に設定した時の探索経路のリストを作成しておきます。
その時のb,Bの値も計算しておくので参考にしてください。

**Comment by NorihiroNakaoka** [comment]
非常に助かり

**Comment by NorihiroNakaoka** [comment]
memo
[s27_reference.xlsx](https://github.com/ehimetakahashilab/TPI_implementation/files/3429733/s27_reference.xlsx)
![IMG_1433](https://user-images.githubusercontent.com/16035056/61846211-36b1b000-aee1-11e9-973d-5a0ead345120.JPG)

**Comment by MaineK00n** [comment]
s27回路
[s27_reference(修正).xlsx](https://github.com/ehimetakahashilab/TPI_implementation/files/3530108/s27_reference.xlsx)
